"""Notebook-specific software and parameter explanations."""

GUIDES = {'01': '## Software and configurable values\n'
       '\n'
       'This notebook introduces data access. `dataset_pipeline.py` contains the shared '
       'loading,\n'
       'validation, grouping, transformation, and export rules so later notebooks use '
       'identical data.\n'
       '\n'
       '- `pathlib`, `urllib`, and `hashlib` locate, download, and verify the public file.\n'
       '- `h5py` reads the MATLAB v7.3/HDF5 data; NumPy stores cycles as\n'
       '  `(cycles, sensors, samples)` arrays.\n'
       "- scikit-learn's `GroupShuffleSplit` keeps every UGM ID in exactly one split.\n"
       '\n'
       '`transform` can be `stored` or the additional `log1p` transformation. Sensor A, '
       'channel 0,\n'
       'and a sensor dimension of length one are fixed for this seminar. UGM 1–500 are split '
       'into\n'
       'train, validation, and test; UGM 501–906 form the exclusive `test_extra` set. Never '
       'use either\n'
       'test split for point selection, correlation screening, or hyperparameter selection.\n',
 '02': '## Software, controls, and plot settings\n'
       '\n'
       'Change only `GAS` and `TRANSFORM`, then use **Run All** so every figure uses the same '
       'choice.\n'
       'NumPy loads the arrays and calculates summaries; Matplotlib displays distributions, '
       'ECDFs,\n'
       'scatter plots, signal bands, and temperature profiles. `dataset_pipeline` supplies the '
       'frozen\n'
       'UGM splits and the 48 allowed phase-boundary points.\n'
       '\n'
       'The final single-point line is only an orientation baseline. When reading the figures, '
       'inspect\n'
       'curvature, outliers, changing density, and split differences instead of relying on '
       'one\n'
       'correlation value.\n',
 '03': '## Software, models, and input parameter\n'
       '\n'
       '`GAS` is the only central input. The notebook compares a line on the stored value, a '
       'line on\n'
       '`log1p(x)`, and an empirical power law on the same raw point. NumPy fits their '
       'parameters.\n'
       'All 48 allowed boundary points are ranked by power-law validation RMSE; test and '
       '`test_extra`\n'
       'are used only after the point and model parameters have been fixed. Predictions are '
       'not clipped,\n'
       'so model failure remains visible.\n',
 '04': '## Software, models, and configurable parameters\n'
       '\n'
       'This notebook extends Notebook 03 to several raw points. `GAS` selects the target and\n'
       '`N_FEATURES` selects between 2 and 13 temperatures. A greedy search adds at most one '
       'point per\n'
       'temperature and uses only power-law validation RMSE. The same selected matrix is then '
       'supplied\n'
       'to raw linear, log1p linear, and multi-point power-law models. More features can '
       'increase\n'
       'flexibility, collinearity, and extrapolation risk, so test sets remain untouched '
       'during selection.\n',
 '05': '## Software, physical assumptions, and parameters\n'
       '\n'
       '`GAS`, `N_ALA_SEGMENTS`, and `RIDGE_ALPHAS` control the experiment. '
       '`physics_features.py`\n'
       'extracts start, end, amplitude, initial slope, tau63, first-order response error, and '
       'a threshold\n'
       'quality flag for all 24 temperature phases. ALA breakpoints are learned from the '
       'training median;\n'
       'each segment contributes a mean and slope. Ridge regularization is selected on '
       'validation only.\n'
       '\n'
       'tau63 equals a physical time constant only for an approximately first-order response. '
       'The error\n'
       'and quality flag expose deviations. Scaling, ALA boundaries, and alpha selection never '
       'see test\n'
       'or `test_extra`.\n',
 '06': '## Software, experiment design, and parameters\n'
       '\n'
       'This is intentionally a negative demonstration, not a valid baseline. `GAS`, the ALA '
       'segment\n'
       'count, held-out UGM fraction, and random seed control it. `GroupShuffleSplit` first '
       'reserves\n'
       'complete unknown UGM IDs; `train_test_split` then deliberately splits the remaining '
       'rows and\n'
       'creates UGM leakage. Extra Trees varies from strongly smoothed to highly flexible '
       'through\n'
       '`min_samples_leaf`. The figures contrast recognition of familiar UGMs with '
       'generalization to\n'
       'entirely new mixtures.\n',
 '07': '## Software, distance model, and parameters\n'
       '\n'
       'The experiment adds ALA, phase dynamics, sparse raw values, derivatives, spectra, and '
       'explicitly\n'
       'irrelevant Gaussian controls to distance-weighted k-NN. `k` is selected once on the '
       'compact ALA\n'
       'baseline and then held fixed. Every column is standardized from training statistics so '
       'units do\n'
       'not dominate Euclidean distance. The control features contain no target information; '
       'they expose\n'
       'how irrelevant dimensions dilute meaningful neighborhoods.\n',
 '08': '## Software, search spaces, and FESR controls\n'
       '\n'
       'Two feature-extraction variants (120 equidistant segments and 50 ALA segments) are '
       'combined with\n'
       'Pearson and RFE-LSR selection. Every segment contributes a mean and slope. '
       'PLSRegression maps the\n'
       'selected correlated features to a few latent components. `FEATURE_COUNT_GRID` and\n'
       '`PLS_COMPONENT_GRID` define the small search spaces. Training creates rankings and '
       'model fits;\n'
       'validation selects FE, FS, feature count, and component count. Test and `test_extra` '
       'are final\n'
       'evaluation sets only.\n'}
